services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: always
